[package]
name = "birdeye"
version = "0.1.0"
edition = "2021"
rust-version = "1.83.0"

[dependencies]
solagent-core = "=0.1.5"
solagent-plugin-birdeye = "=0.1.4"
solagent-wallet-solana = "0.1.2"
tokio = { version = "1.42.0", features = ["full"] }
