[workspace]
resolver = "2"
members = [
    "examples/plugin",
    "packages/core",

    "packages/adapters/topkio",

    "packages/adapters/rig/goplus",
    "packages/adapters/rig/solana",
    "packages/adapters/rig/helius",
    "packages/adapters/rig/jupiter", 
    "packages/adapters/rig/rugcheck",

    "packages/plugins/goplus",
    "packages/plugins/solana", 
    "packages/plugins/helius",
    "packages/plugins/jupiter", 
    "packages/plugins/rugcheck", 
]

[workspace.package]
version = "0.1.0"
edition = "2021"

[profile.dev]
opt-level = "z"

[profile.release]
lto = "thin"
strip = true
codegen-units = 1
opt-level = "z"
