[package]
name = "solagent-rig-gibwork"
version = "0.1.0"
edition = "2021"
authors = ["zTgx <beautifularea@gmail.com>"]
repository = "https://github.com/zTgx/solagent.rs"
readme = "README.md"
keywords = ["solagent", "rig", "gibwork"]
license = "Apache 2.0"
description = "solagent.rs rig gibwork"

[dependencies]
solagent-core = { path = "../../../core" }
solagent-plugin-gibwork = { path = "../../../plugins/gibwork" }
serde = { version = "1.0", features = ["derive"] }
thiserror = "2.0.9"
serde_json = "1.0"